# Generated by Django 5.0.9 on 2026-06-13 00:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover')),
                ('stream_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('scheduled', 'Programmé'), ('recorded', 'Enregistré')], db_index=True, default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hosts', models.ManyToManyField(blank=True, related_name='emissions', to='artists.artist')),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['status', '-scheduled_at'], name='emissions_e_status_9c8d52_idx')],
            },
        ),
    ]
