# Generated by Django 6.0.6 on 2026-07-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_remove_emission_cf_live_input_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='stream_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
