# Generated by Django 6.0.6 on 2026-07-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_alter_emission_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='recording_status',
            field=models.CharField(choices=[('none', 'Aucun'), ('pending', 'En cours de traitement'), ('ready', 'Disponible'), ('failed', 'Échec')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='emission',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
