from rest_framework import serializers

from .validation import _extract_public_id, verify_cloudinary_asset


def resolve_cloudinary_url(field_value, resource_type="image"):
    """Returns a real, loadable URL for a `CloudinaryField`'s current value, regardless of
    whether it's already a `CloudinaryResource` (the case whenever the instance was freshly
    loaded from the DB — the normal case for every GET) or still a bare string (the in-memory
    state of an instance that was just created/updated and returned directly in the same
    request/response, before ever being reloaded — `CloudinaryField`'s descriptor only wraps a
    value as a `CloudinaryResource` with a working `.url` on load from the database).

    Every `get_xxx_url(self, obj): return obj.field.url if obj.field else None` pattern in this
    codebase needs this instead of a bare `.url` access, or it 500s on precisely the requests
    where a Cloudinary-backed field was just set in the very same request that reads it back —
    e.g. `POST /artists/{slug}/gallery/` (write + immediate serialize of the same instance,
    never reloaded) 500ing on any successful upload.
    """
    if not field_value:
        return None
    if hasattr(field_value, "url"):
        return field_value.url
    from cloudinary.utils import cloudinary_url

    url, _options = cloudinary_url(str(field_value), resource_type=resource_type, secure=True)
    return url


class CloudinaryUrlField(serializers.CharField):
    """Bridges a model `CloudinaryField` to the API for writing.

    DRF has no built-in mapping for `cloudinary.models.CloudinaryField` — left to the default
    `ModelSerializer`, it falls back to `rest_framework.fields.ModelField`, which performs *no*
    validation at all and stores whatever string it's given verbatim. Combined with Cloudinary's
    own SDK behavior of echoing back any value that already looks like a URL completely
    unmodified (instead of regenerating one), that let a truncated paste (`https://res.cloudinary`)
    or a non-secure URL (`http://...`) get stored and served to clients byte-for-byte forever.

    Accepts either:
    - A bare Cloudinary public_id (what the field naturally holds when set via Django admin's
      native upload widget) — passed straight through untouched.
    - A full Cloudinary URL (what the signed direct-upload flow hands the frontend, which then
      PATCHes/POSTs it back here) — verified against our own Cloudinary account (rejecting
      anything malformed, incomplete, or not actually a real uploaded asset) and reduced to
      just its public_id before being stored. Storing only the public_id means `.url` is always
      freshly regenerated by the SDK (guaranteed https) rather than a raw stored string being
      echoed back as-is.
    """

    def __init__(self, *args, resource_type="image", **kwargs):
        self.resource_type = resource_type
        super().__init__(*args, **kwargs)

    def to_internal_value(self, data):
        if not isinstance(data, str):
            raise serializers.ValidationError("Ce champ doit être une chaîne de caractères.")
        value = data.strip()
        if not value or not value.lower().startswith("http"):
            return value  # already a public_id, or blank — nothing to validate/convert

        # Accept either scheme on the way in — the asset check below only recognizes https,
        # and we're about to reduce this to a public_id anyway, so the caller's scheme choice
        # doesn't matter as long as it's genuinely our account's asset.
        normalized = "https://" + value.split("://", 1)[1] if value.lower().startswith("http://") else value

        verify_cloudinary_asset(normalized, self.resource_type)  # raises ValidationError if invalid
        parsed = _extract_public_id(normalized)
        if parsed is None:
            # Verified but not one of our own Cloudinary assets (an externally-hosted URL that
            # passed verify_cloudinary_asset's external-host check, e.g. a trusted embed host or
            # any other public URL) — nothing to reduce to a public_id, store the URL as-is.
            # Without this branch, ANY non-own-account URL crashed here with an unhandled
            # TypeError (unpacking None) the moment validation succeeded for it.
            return normalized
        public_id, _resource_type = parsed
        return public_id

    def to_representation(self, value):
        return resolve_cloudinary_url(value, self.resource_type)
