[mypy]
plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = settings.local

[mypy-allauth.*]
ignore_missing_imports = True

[mypy-dj_rest_auth.*]
ignore_missing_imports = True

[mypy-rest_framework.*]
ignore_missing_imports = True

[mypy-rest_framework_simplejwt.*]
ignore_missing_imports = True

[mypy-cloudinary.*]
ignore_missing_imports = True

[mypy-celery.*]
ignore_missing_imports = True

[mypy-django_celery_beat.*]
ignore_missing_imports = True

[mypy-django_redis.*]
ignore_missing_imports = True

[mypy-django_filters.*]
ignore_missing_imports = True

[mypy-drf_spectacular.*]
ignore_missing_imports = True

[mypy-django_db_connection_pool.*]
ignore_missing_imports = True

[mypy-decouple.*]
ignore_missing_imports = True

[mypy-faker.*]
ignore_missing_imports = True
