# Generated by Django 6.0.6 on 2026-06-13 14:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover')),
                ('category', models.CharField(choices=[('talk', 'Talk'), ('culture', 'Culture'), ('musique', 'Musique'), ('societe', 'Société'), ('jeunesse', 'Jeunesse'), ('sport', 'Sport')], db_index=True, max_length=30)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('episode_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'podcast series',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_featured'], name='podcasts_po_categor_f42940_idx')],
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover')),
                ('audio_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio_file')),
                ('audio_url', models.URLField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('episode_number', models.PositiveSmallIntegerField(default=1)),
                ('season_number', models.PositiveSmallIntegerField(default=1)),
                ('guests', models.JSONField(blank=True, default=list)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.podcastseries')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['series', '-published_at'], name='podcasts_po_series__8d4f59_idx'), models.Index(fields=['is_featured', '-published_at'], name='podcasts_po_is_feat_d8bce2_idx')],
            },
        ),
    ]
