# Generated by Django 6.0.6 on 2026-07-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
