# Generated by Django 6.0.6 on 2026-07-21 19:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_podcastepisode_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastseries',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio_file'),
        ),
        migrations.AddField(
            model_name='podcastseries',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='podcastseries',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='podcastseries',
            name='is_series',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
