# Generated by Django 6.0.6 on 2026-07-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_podcastseries_audio_file_podcastseries_audio_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='podcastseries',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
