# Generated by Django 6.0.6 on 2026-07-21 22:17

from django.db import migrations


def _normalize_guest(entry):
    """Same rules as GuestSerializer.to_representation (apps/podcasts/serializers.py), applied
    once in place instead of only defended against at read time. `guests` was a completely
    unvalidated JSONField before GuestSerializer existed, so rows written before that carry a
    bare string, an old/foreign dict shape (e.g. the admin dashboard's {name, role, avatar}), or
    outright garbage. Already-canonical entries (already written through the new API) round-trip
    unchanged.

    Returns None if the entry carries no usable name at all — the caller drops those rather
    than keeping a nameless, informationless placeholder.
    """
    if isinstance(entry, str):
        name = entry.strip()
        return {"name": name, "artist_id": None, "user_id": None} if name else None

    if isinstance(entry, dict):
        name = entry.get("name")
        if not isinstance(name, str) or not name.strip():
            return None
        artist_id = entry.get("artist_id")
        user_id = entry.get("user_id")
        return {
            "name": name.strip(),
            "artist_id": artist_id if isinstance(artist_id, int) else None,
            "user_id": user_id if isinstance(user_id, int) else None,
        }

    return None


def normalize_guests(apps, schema_editor):
    PodcastEpisode = apps.get_model("podcasts", "PodcastEpisode")
    to_update = []
    for episode in PodcastEpisode.objects.exclude(guests=[]).only("id", "guests"):
        if not isinstance(episode.guests, list):
            episode.guests = []
            to_update.append(episode)
            continue
        normalized = [g for g in (_normalize_guest(entry) for entry in episode.guests) if g is not None]
        if normalized != episode.guests:
            episode.guests = normalized
            to_update.append(episode)
    if to_update:
        PodcastEpisode.objects.bulk_update(to_update, ["guests"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0004_alter_podcastepisode_audio_url_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_guests, migrations.RunPython.noop),
    ]
