# Generated by Django 6.0.6 on 2026-07-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_normalize_legacy_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='published', max_length=20),
        ),
    ]
