# Generated by Django 6.0.6 on 2026-07-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='cta_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
