# Generated by Django 6.0.6 on 2026-07-25 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0002_alter_homebanner_cta_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='title_highlight',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='FeaturedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text="ID numérique de l'objet — visible dans son URL d'admin (ex. /admin/artists/artist/12/change/ → 12).")),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'artists'), ('model', 'artist')), models.Q(('app_label', 'emissions'), ('model', 'emission')), models.Q(('app_label', 'radio'), ('model', 'radioprogram')), models.Q(('app_label', 'webtv'), ('model', 'webtvvideo')), models.Q(('app_label', 'live_music'), ('model', 'musiclivesession')), models.Q(('app_label', 'events'), ('model', 'event')), models.Q(('app_label', 'releases'), ('model', 'musicrelease')), models.Q(('app_label', 'articles'), ('model', 'article')), models.Q(('app_label', 'podcasts'), ('model', 'podcastepisode')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Contenu à la une',
                'verbose_name_plural': 'Contenus à la une',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
