# Generated by Django 6.0.6 on 2026-07-11 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_live_input_uid', models.CharField(blank=True, max_length=64)),
                ('cf_rtmps_url', models.URLField(blank=True)),
                ('cf_rtmps_key', models.CharField(blank=True, max_length=128)),
                ('cf_playback_hls_url', models.URLField(blank=True)),
                ('cf_playback_dash_url', models.URLField(blank=True)),
                ('live_started_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('scheduled', 'Programmé'), ('ended', 'Terminé')], db_index=True, default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artists', models.ManyToManyField(blank=True, related_name='live_music_sessions', to='artists.artist')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='live_music__status_63d113_idx')],
            },
        ),
        migrations.CreateModel(
            name='MusicLiveSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True, default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_music_slots', to='artists.artist')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['day_of_week', 'start_time'], name='live_music__day_of__da953f_idx')],
            },
        ),
    ]
