# Generated by Django 6.0.6 on 2026-07-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_music', '0002_musiclivesession_cover_musiclivesession_scheduled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiclivesession',
            name='cf_live_input_uid',
        ),
        migrations.RemoveField(
            model_name='musiclivesession',
            name='cf_playback_dash_url',
        ),
        migrations.RemoveField(
            model_name='musiclivesession',
            name='cf_playback_hls_url',
        ),
        migrations.RemoveField(
            model_name='musiclivesession',
            name='cf_rtmps_key',
        ),
        migrations.RemoveField(
            model_name='musiclivesession',
            name='cf_rtmps_url',
        ),
        migrations.AddField(
            model_name='musiclivesession',
            name='playback_hls_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='musiclivesession',
            name='stream_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
