# Generated by Django 5.0.9 on 2026-06-13 00:51

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('cover', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover')),
                ('release_date', models.DateField(db_index=True)),
                ('format', models.CharField(choices=[('album', 'Album'), ('single', 'Single'), ('clip', 'Clip'), ('documentaire', 'Documentaire'), ('expo', 'Exposition')], db_index=True, max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_premiere', models.BooleanField(default=False)),
                ('streaming_links', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('preview_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_releases', to='artists.artist')),
            ],
            options={
                'ordering': ['-release_date'],
                'indexes': [models.Index(fields=['-release_date', 'format'], name='releases_mu_release_40cb7b_idx'), models.Index(fields=['is_featured'], name='releases_mu_is_feat_538d31_idx'), models.Index(fields=['artist', '-release_date'], name='releases_mu_artist__4f3957_idx')],
            },
        ),
    ]
