# Generated by Django 6.0.6 on 2026-07-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicrelease',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
