# Generated by Django 5.0.9 on 2026-06-13 00:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTVVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail')),
                ('video_url', models.URLField()),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(choices=[('freestyles', 'Freestyles'), ('studio_sessions', 'Studio Sessions'), ('docs', 'Documentaires'), ('interviews', 'Interviews'), ('premiers', 'Premières')], db_index=True, max_length=30)),
                ('is_premier', models.BooleanField(db_index=True, default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artists', models.ManyToManyField(blank=True, related_name='webtv_videos', to='artists.artist')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['category', '-published_at'], name='webtv_webtv_categor_27a8dc_idx'), models.Index(fields=['is_premier', '-published_at'], name='webtv_webtv_is_prem_8b4e2d_idx')],
            },
        ),
    ]
