# Generated by Django 6.0.6 on 2026-07-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtvvideo',
            name='cf_live_input_uid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='webtvvideo',
            name='cf_playback_dash_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='webtvvideo',
            name='cf_playback_hls_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='webtvvideo',
            name='cf_rtmps_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='webtvvideo',
            name='cf_rtmps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='webtvvideo',
            name='live_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
