# Generated by Django 6.0.6 on 2026-07-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtv', '0002_webtvvideo_cf_live_input_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtvvideo',
            name='category',
            field=models.CharField(choices=[('freestyles', 'Freestyles'), ('studio_sessions', 'Studio Sessions'), ('docs', 'Documentaires'), ('interviews', 'Interviews'), ('premiers', 'Premières'), ('concerts', 'Concerts')], db_index=True, max_length=30),
        ),
    ]
