# Generated by Django 6.0.6 on 2026-07-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtv', '0004_remove_webtvvideo_cf_live_input_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtvvideo',
            name='video_url',
            field=models.URLField(max_length=500),
        ),
    ]
