# Generated by Django 6.0.6 on 2026-07-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtv', '0005_alter_webtvvideo_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtvvideo',
            name='broadcast_mode',
            field=models.CharField(choices=[('playout', 'Playout'), ('camera', 'Caméra')], default='playout', max_length=20),
        ),
        migrations.AlterField(
            model_name='webtvvideo',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
