# Generated by Django 6.0.6 on 2026-07-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtv', '0006_webtvvideo_broadcast_mode_alter_webtvvideo_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtvvideo',
            name='playout_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='webtvvideo',
            name='recording_status',
            field=models.CharField(choices=[('none', 'Aucun'), ('pending', 'En cours de traitement'), ('ready', 'Disponible'), ('failed', 'Échec')], default='none', max_length=20),
        ),
    ]
