# Generated by Django 6.0.6 on 2026-07-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_alter_radioprogram_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioprogram',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='radioprogram',
            name='recording_status',
            field=models.CharField(choices=[('none', 'Aucun'), ('pending', 'En cours de traitement'), ('ready', 'Disponible'), ('failed', 'Échec')], default='none', max_length=20),
        ),
    ]
