# Generated by Django 6.0.6 on 2026-07-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
