# Generated by Django 6.0.6 on 2026-07-21 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_postlike_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='community.challenge'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='is_pinned_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='post_type',
            field=models.CharField(choices=[('talent', 'Talent'), ('art', 'Art'), ('news', 'News'), ('challenge_response', 'Challenge Response')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['challenge', '-created_at'], name='community_c_challen_db2479_idx'),
        ),
    ]
